# Generated by Django 4.1.4 on 2022-12-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_management_app', '0003_subjects_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='staff',
        ),
        migrations.AddField(
            model_name='subjects',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, to='college_management_app.staffs'),
        ),
    ]
