# Generated by Django 4.1.4 on 2022-12-22 17:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('college_management_app', '0006_remove_subjects_staff_messagetostudent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetostaff',
            options={'ordering': ['is_read', '-created']},
        ),
        migrations.AlterModelOptions(
            name='messagetostudent',
            options={'ordering': ['is_read', '-created']},
        ),
        migrations.AddField(
            model_name='staffs',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AssignmentSubmit',
            fields=[
                ('files', models.FileField(upload_to='Files/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_management_app.staffs')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college_management_app.students')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('task', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_management_app.staffs')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college_management_app.subjects')),
            ],
        ),
    ]
